In [553]:
import pandas as pd

In [533]:
weather_data = pd.read_csv('./data/real/weather_data.csv')
last_temp = pd.read_csv('./data/real/3rdyr.csv')
last_hi = pd.read_csv('./data/real/3yrHI.csv')
last_p = pd.read_csv('./data/real/3yrP.csv')
last_V = pd.read_csv('./data/real/3yrV.csv')
last_W = pd.read_csv('./data/real/3yrW.csv')
last_WC = pd.read_csv('./data/real/3yrWC.csv')
pd.set_option('display.max_columns', None)
weather_data.tail()

,DateTime,Temperature,Dew Point,Relative Humidity,One Hour Precipitation,Heat Index,Wind Chill,Wind Speed,Gust,Direction,Visibility
17485,7/31/2024 15:52,35.6,19.53,38.81,0.0,37.97,NaN,17,NaN,280,10.0
17486,7/31/2024 16:52,34.4,19.01,40.20,0.0,36.18,NaN,17,30.0,260,10.0
17487,7/31/2024 17:52,34.4,19.51,41.47,0.0,36.54,NaN,15,NaN,260,10.0
17488,7/31/2024 18:52,31.1,21.74,57.50,0.0,34.44,NaN,9,NaN,160,10.0
17489,7/31/2024 19:52,30.0,21.13,59.02,0.0,32.64,NaN,15,NaN,160,10.0

In [534]:
last_temp.head()

              DateTime  Temperature  Dew Point  Relative Humidity
0  2024-07-31 20:52:00         28.9      20.62              60.97
1  2024-07-31 21:52:00         27.8      20.61              64.99
2  2024-07-31 22:52:00         26.7      20.61              69.31
3  2024-07-31 23:52:00         25.6      20.60              73.95
4  2024-08-01 00:52:00         24.4      20.60              79.42

In [535]:
last_temp['One Hour Precipitation'] = last_p['One Hour Precipitation']
last_temp['Heat Index'] = last_hi['Heat Index']
last_temp['Wind Chill'] = last_WC['Wind Chill']
last_temp['Wind Speed'] = last_W['Wind Speed']
last_temp['Gust'] = last_W['Gust']
last_temp['Direction'] = last_W['Direction']
last_temp['Visibility'] = last_V['Visibility']

last_temp.head()

,DateTime,Temperature,Dew Point,Relative Humidity,One Hour Precipitation,Heat Index,Wind Chill,Wind Speed,Gust,Direction,Visibility
0,2024-07-31 20:52:00,28.9,20.62,60.97,0.0,31.01,NaN,9,NaN,160,10.0
1,2024-07-31 21:52:00,27.8,20.61,64.99,0.0,29.70,NaN,13,NaN,180,10.0
2,2024-07-31 22:52:00,26.7,20.61,69.31,0.0,28.31,NaN,9,NaN,190,10.0
3,2024-07-31 23:52:00,25.6,20.60,73.95,0.0,NaN,NaN,0,NaN,0,10.0
4,2024-08-01 00:52:00,24.4,20.60,79.42,0.0,NaN,NaN,0,NaN,0,10.0

In [536]:
weather = pd.concat((weather_data, last_temp))
print(len(weather_data), len(last_temp), len(weather), (len(weather_data) + len(last_temp)))
weather.head()

17490 8757 26247 26247

,DateTime,Temperature,Dew Point,Relative Humidity,One Hour Precipitation,Heat Index,Wind Chill,Wind Speed,Gust,Direction,Visibility
0,7/31/2022 20:52,21.7,21.1,96.40,76.2,NaN,NaN,0,NaN,0,9.0
1,7/31/2022 21:52,21.7,21.1,96.40,0.0,NaN,NaN,6,NaN,170,7.0
2,7/31/2022 22:52,21.7,21.1,96.40,0.0,NaN,NaN,6,NaN,220,7.0
3,7/31/2022 23:52,21.7,20.6,93.48,0.0,NaN,NaN,6,NaN,240,8.0
4,8/1/2022 00:52,21.7,20.6,93.48,0.0,NaN,NaN,0,NaN,0,9.0

In [537]:
weather.tail()

,DateTime,Temperature,Dew Point,Relative Humidity,One Hour Precipitation,Heat Index,Wind Chill,Wind Speed,Gust,Direction,Visibility
8752,2025-08-01 15:52:00,22.2,17.79,76.19,0.00,NaN,NaN,9,NaN,40,10.0
8753,2025-08-01 16:52:00,22.2,18.29,78.61,0.00,NaN,NaN,9,NaN,50,10.0
8754,2025-08-01 17:52:00,22.2,17.79,76.19,2.54,NaN,NaN,17,NaN,30,10.0
8755,2025-08-01 18:52:00,22.2,17.79,76.19,0.00,NaN,NaN,17,NaN,30,10.0
8756,2025-08-01 19:52:00,21.7,17.79,78.54,0.00,NaN,NaN,13,NaN,40,10.0

In [538]:
weather['DateTime'] = pd.to_datetime(weather['DateTime'], format='mixed')
weather['Hour'] = weather['DateTime'].dt.hour
weather['Date'] = weather['DateTime'].dt.date
weather = weather[['DateTime', 'Date', 'Hour', 'Temperature', 'Dew Point', 'Relative Humidity', 'One Hour Precipitation', 'Heat Index', 'Wind Chill', 'Wind Speed', 'Gust', 'Direction', 'Visibility']]
weather = weather.reset_index().drop('index', axis=1)
weather = weather.sort_values(['Date', 'Hour'])
weather.head()

,DateTime,Date,Hour,Temperature,Dew Point,Relative Humidity,One Hour Precipitation,Heat Index,Wind Chill,Wind Speed,Gust,Direction,Visibility
0,2022-07-31 20:52:00,2022-07-31,20,21.7,21.1,96.40,76.2,NaN,NaN,0,NaN,0,9.0
1,2022-07-31 21:52:00,2022-07-31,21,21.7,21.1,96.40,0.0,NaN,NaN,6,NaN,170,7.0
2,2022-07-31 22:52:00,2022-07-31,22,21.7,21.1,96.40,0.0,NaN,NaN,6,NaN,220,7.0
3,2022-07-31 23:52:00,2022-07-31,23,21.7,20.6,93.48,0.0,NaN,NaN,6,NaN,240,8.0
4,2022-08-01 00:52:00,2022-08-01,0,21.7,20.6,93.48,0.0,NaN,NaN,0,NaN,0,9.0

In [539]:
hour = weather['Hour'] == 19
date = weather['Date'] == pd.Timestamp('2025-07-31').date()
display(weather.loc[hour& date])
print(len(weather))

,DateTime,Date,Hour,Temperature,Dew Point,Relative Humidity,One Hour Precipitation,Heat Index,Wind Chill,Wind Speed,Gust,Direction,Visibility
26222,2025-07-31 19:52:00,2025-07-31,19,24.4,22.8,90.83,0.0,NaN,NaN,15,NaN,330,10.0

26247

In [540]:
weather.tail()

,DateTime,Date,Hour,Temperature,Dew Point,Relative Humidity,One Hour Precipitation,Heat Index,Wind Chill,Wind Speed,Gust,Direction,Visibility
26242,2025-08-01 15:52:00,2025-08-01,15,22.2,17.79,76.19,0.00,NaN,NaN,9,NaN,40,10.0
26243,2025-08-01 16:52:00,2025-08-01,16,22.2,18.29,78.61,0.00,NaN,NaN,9,NaN,50,10.0
26244,2025-08-01 17:52:00,2025-08-01,17,22.2,17.79,76.19,2.54,NaN,NaN,17,NaN,30,10.0
26245,2025-08-01 18:52:00,2025-08-01,18,22.2,17.79,76.19,0.00,NaN,NaN,17,NaN,30,10.0
26246,2025-08-01 19:52:00,2025-08-01,19,21.7,17.79,78.54,0.00,NaN,NaN,13,NaN,40,10.0

In [541]:
weather.iloc[-10]

DateTime                  2025-08-01 10:52:00
Date                               2025-08-01
Hour                                       10
Temperature                              19.4
Dew Point                               17.79
Relative Humidity                       90.49
One Hour Precipitation                   2.54
Heat Index                                NaN
Wind Chill                                NaN
Wind Speed                                 17
Gust                                      NaN
Direction                                  30
Visibility                                3.0
Name: 26237, dtype: object

In [542]:
# weather['DateTime'] = pd.to_datetime(weather['Date'].astype(str) + ' ' + weather['Hour'].astype(int).astype(str) + ':00')

# Define start and end times
start_time = pd.Timestamp('2022-07-31 20:00:00')
end_time = pd.Timestamp('2025-07-31 19:00:00')

start_time = weather.iloc[0]['DateTime']
end_time = weather.iloc[-1]['DateTime']
#end_time = pd.Timestamp('2025-07-31 19:00:00')
# Generate full expected hourly range
expected_times = pd.date_range(start=start_time, end=end_time, freq='h')

# Identify which timestamps are missing
actual_times = set(weather['DateTime'])
missing_times = [t for t in expected_times if t not in actual_times]

# Display number of missing timestamps and a sample (if any)
len(missing_times), missing_times[:10]

(88,
 [Timestamp('2022-08-02 13:52:00'),
  Timestamp('2022-08-02 14:52:00'),
  Timestamp('2022-08-30 15:52:00'),
  Timestamp('2022-10-31 12:52:00'),
  Timestamp('2022-11-04 08:52:00'),
  Timestamp('2023-02-14 10:52:00'),
  Timestamp('2023-03-12 02:52:00'),
  Timestamp('2023-03-21 12:52:00'),
  Timestamp('2023-03-29 09:52:00'),
  Timestamp('2023-04-05 04:52:00')])

In [543]:
weather = weather.drop_duplicates(subset='DateTime', keep='first')

weather = weather.set_index('DateTime').reindex(expected_times)

# Restore Date and Hour columns
weather['Date'] = weather.index.date
weather['Hour'] = weather.index.hour
weather = weather.reset_index(drop=True)

In [544]:
display(weather.head())
display(weather.tail())

,Date,Hour,Temperature,Dew Point,Relative Humidity,One Hour Precipitation,Heat Index,Wind Chill,Wind Speed,Gust,Direction,Visibility
0,2022-07-31,20,21.7,21.1,96.40,76.2,NaN,NaN,0.0,NaN,0.0,9.0
1,2022-07-31,21,21.7,21.1,96.40,0.0,NaN,NaN,6.0,NaN,170.0,7.0
2,2022-07-31,22,21.7,21.1,96.40,0.0,NaN,NaN,6.0,NaN,220.0,7.0
3,2022-07-31,23,21.7,20.6,93.48,0.0,NaN,NaN,6.0,NaN,240.0,8.0
4,2022-08-01,0,21.7,20.6,93.48,0.0,NaN,NaN,0.0,NaN,0.0,9.0

,Date,Hour,Temperature,Dew Point,Relative Humidity,One Hour Precipitation,Heat Index,Wind Chill,Wind Speed,Gust,Direction,Visibility
26323,2025-08-01,15,22.2,17.79,76.19,0.00,NaN,NaN,9.0,NaN,40.0,10.0
26324,2025-08-01,16,22.2,18.29,78.61,0.00,NaN,NaN,9.0,NaN,50.0,10.0
26325,2025-08-01,17,22.2,17.79,76.19,2.54,NaN,NaN,17.0,NaN,30.0,10.0
26326,2025-08-01,18,22.2,17.79,76.19,0.00,NaN,NaN,17.0,NaN,30.0,10.0
26327,2025-08-01,19,21.7,17.79,78.54,0.00,NaN,NaN,13.0,NaN,40.0,10.0

In [545]:
hour = weather['Hour'] == 19
date = weather['Date'] == pd.Timestamp('2025-07-31').date()
display(weather.loc[hour& date])
print(len(weather))

,Date,Hour,Temperature,Dew Point,Relative Humidity,One Hour Precipitation,Heat Index,Wind Chill,Wind Speed,Gust,Direction,Visibility
26303,2025-07-31,19,24.4,22.8,90.83,0.0,NaN,NaN,15.0,NaN,330.0,10.0

26328

In [546]:
weather = weather[:26304]
display(weather.head())
display(weather.tail())

,Date,Hour,Temperature,Dew Point,Relative Humidity,One Hour Precipitation,Heat Index,Wind Chill,Wind Speed,Gust,Direction,Visibility
0,2022-07-31,20,21.7,21.1,96.40,76.2,NaN,NaN,0.0,NaN,0.0,9.0
1,2022-07-31,21,21.7,21.1,96.40,0.0,NaN,NaN,6.0,NaN,170.0,7.0
2,2022-07-31,22,21.7,21.1,96.40,0.0,NaN,NaN,6.0,NaN,220.0,7.0
3,2022-07-31,23,21.7,20.6,93.48,0.0,NaN,NaN,6.0,NaN,240.0,8.0
4,2022-08-01,0,21.7,20.6,93.48,0.0,NaN,NaN,0.0,NaN,0.0,9.0

,Date,Hour,Temperature,Dew Point,Relative Humidity,One Hour Precipitation,Heat Index,Wind Chill,Wind Speed,Gust,Direction,Visibility
26299,2025-07-31,15,27.2,24.4,84.74,0.0,30.71,NaN,37.0,56.0,190.0,10.0
26300,2025-07-31,16,27.2,23.9,82.24,0.0,30.43,NaN,15.0,NaN,140.0,10.0
26301,2025-07-31,17,23.3,22.2,93.56,254.0,NaN,NaN,19.0,43.0,320.0,2.0
26302,2025-07-31,18,24.4,23.3,93.61,482.6,NaN,NaN,11.0,NaN,60.0,10.0
26303,2025-07-31,19,24.4,22.8,90.83,0.0,NaN,NaN,15.0,NaN,330.0,10.0

In [547]:
internet = pd.read_csv('./data/real/internet.csv')
internet.head()

        date  hour  avg_download_speed_mbps  num_tests
0  7/31/2022  20.0               126.631161      373.0
1  7/31/2022  21.0               123.800714      299.0
2  7/31/2022  22.0               127.846609      302.0
3  7/31/2022  23.0               115.075041      262.0
4   8/1/2022   0.0               149.462286      226.0

In [548]:
internet['date'] = pd.to_datetime(internet['date'], format='mixed')
internet = internet.rename({
    'date' : 'Date',
    'hour' : 'Hour',
    'avg_download_speed_mbps' : 'Download Speed',
    'num_tests' : 'Test Count'
    }, axis=1)
internet = internet.dropna(subset=['Hour'])
internet['Hour'] = internet['Hour'].astype(int)
print(len(internet), len(weather))
internet.head()

26304 26304

        Date  Hour  Download Speed  Test Count
0 2022-07-31    20      126.631161       373.0
1 2022-07-31    21      123.800714       299.0
2 2022-07-31    22      127.846609       302.0
3 2022-07-31    23      115.075041       262.0
4 2022-08-01     0      149.462286       226.0

In [549]:
for df in [weather, internet]:
    df['Date'] = pd.to_datetime(df['Date']).dt.date
    df['Hour'] = pd.to_numeric(df['Hour']).astype(int)

In [550]:
weather.to_csv('./data/real/all_weather_data.csv')
internet.to_csv('./data/real/all_internet_data.csv')

In [551]:
full_data = pd.merge(weather, internet, on=['Date', 'Hour'])
print(len(full_data))
display(full_data.head())
display(full_data.tail())

26304

,Date,Hour,Temperature,Dew Point,Relative Humidity,One Hour Precipitation,Heat Index,Wind Chill,Wind Speed,Gust,Direction,Visibility,Download Speed,Test Count
0,2022-07-31,20,21.7,21.1,96.40,76.2,NaN,NaN,0.0,NaN,0.0,9.0,126.631161,373.0
1,2022-07-31,21,21.7,21.1,96.40,0.0,NaN,NaN,6.0,NaN,170.0,7.0,123.800714,299.0
2,2022-07-31,22,21.7,21.1,96.40,0.0,NaN,NaN,6.0,NaN,220.0,7.0,127.846609,302.0
3,2022-07-31,23,21.7,20.6,93.48,0.0,NaN,NaN,6.0,NaN,240.0,8.0,115.075041,262.0
4,2022-08-01,0,21.7,20.6,93.48,0.0,NaN,NaN,0.0,NaN,0.0,9.0,149.462286,226.0

,Date,Hour,Temperature,Dew Point,Relative Humidity,One Hour Precipitation,Heat Index,Wind Chill,Wind Speed,Gust,Direction,Visibility,Download Speed,Test Count
26299,2025-07-31,15,27.2,24.4,84.74,0.0,30.71,NaN,37.0,56.0,190.0,10.0,165.308690,312.0
26300,2025-07-31,16,27.2,23.9,82.24,0.0,30.43,NaN,15.0,NaN,140.0,10.0,137.707236,372.0
26301,2025-07-31,17,23.3,22.2,93.56,254.0,NaN,NaN,19.0,43.0,320.0,2.0,138.005676,286.0
26302,2025-07-31,18,24.4,23.3,93.61,482.6,NaN,NaN,11.0,NaN,60.0,10.0,171.444877,311.0
26303,2025-07-31,19,24.4,22.8,90.83,0.0,NaN,NaN,15.0,NaN,330.0,10.0,192.592295,350.0

In [552]:
full_data.to_csv('./data/real/capstone_data.csv')